# Generated by Django 5.1.1 on 2024-09-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_alter_customuser_parent_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="child_dob",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="child_first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="child_gender",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="child_last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="parent_contact_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="parent_email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="parent_first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="parent_gender",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="parent_last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="school_medium",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="school_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
